In [2]:
import numpy as np
l = [1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [15]:
print(arr[[1,2]])

[2 3]


In [16]:
cond = arr > 2 # 筛选大于2的数据

In [17]:
arr[cond]

array([3, 4, 5])

## 其他创建方式

In [18]:
np.ones(shape = 10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.zeros(shape=5)

array([0., 0., 0., 0., 0.])

In [20]:
np.full(shape=20, fill_value=123
    )

array([123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123, 123,
       123, 123, 123, 123, 123, 123, 123])

In [23]:
np.random.randint(0,100, size=20)

array([73, 93, 84, 30, 59, 97, 50, 20, 21, 57, 56, 38, 58, 88, 90,  1, 26,
       89, 10, 17])

In [24]:
np.random.randn(10) # 正态分布，平均值是0，标准差是1

array([ 0.48089386,  1.14570779, -0.99452659,  1.65446699,  0.41357645,
       -0.95170634,  0.08070671,  0.34448619,  1.16187314, -0.52531897])

In [27]:
np.linspace(1, 99  ,50) # 等差数列

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23., 25.,
       27., 29., 31., 33., 35., 37., 39., 41., 43., 45., 47., 49., 51.,
       53., 55., 57., 59., 61., 63., 65., 67., 69., 71., 73., 75., 77.,
       79., 81., 83., 85., 87., 89., 91., 93., 95., 97., 99.])

In [32]:
np.set_printoptions(suppress=True)
np.logspace(0,10, base=3, num=11)
# shift +  tab 查看参数

array([    1.,     3.,     9.,    27.,    81.,   243.,   729.,  2187.,
        6561., 19683., 59049.])

In [37]:
np.random.randint(0, 10, size = (3,2,))

array([[1, 9],
       [6, 9],
       [5, 0]])

In [38]:
np.random.randint(0, 10, size = (3,2,3))

array([[[0, 1, 9],
        [7, 5, 5]],

       [[0, 5, 9],
        [5, 3, 4]],

       [[7, 6, 2],
        [1, 4, 1]]])

In [39]:
np.random.random(20 )

array([0.90168442, 0.44784339, 0.37360455, 0.2142776 , 0.34416622,
       0.25594691, 0.83779516, 0.92884621, 0.10356776, 0.95132329,
       0.70396678, 0.04811042, 0.8155584 , 0.0983242 , 0.08794847,
       0.68930411, 0.20486441, 0.51660442, 0.76732262, 0.68721401])

## 数据查看

In [ ]:
arr = np.random.random(size=(3,5))

In [ ]:
arr.shape # 数组的形状

In [5]:
arr.dtype

dtype('float64')

In [12]:
arr.size # 数组的大小

15

In [8]:
arr.ndim # 数组纬度

2

In [11]:
arr.itemsize # 每个元素的大小

8

# 文件io

## 保存npy

In [18]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr = np.arange(0,10, 3)
arr

array([0, 3, 6, 9])

In [22]:
np.save('./data1', arr)

In [24]:
np.load('./data1.npy')

array([0, 3, 6, 9])

## 保存npz

In [25]:
arr2 = np.logspace(0,10,base=2,num=11)

In [26]:
np.savez('./data2',x=arr,y=arr2)

In [28]:
data = np.load('./data2.npz')

In [30]:
data['x']

array([0, 3, 6, 9])

In [33]:
data['y']

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,
        512., 1024.])

## 数据类型

In [35]:
arr = np.array([2,4,5,6], dtype=np.int32)

In [36]:
arr

array([2, 4, 5, 6])

In [37]:
arr = np.random.randint(0, 100,size=(50,100), dtype= np.int32)

In [38]:
np.save('data3_in32', arr)

In [39]:
arr = np.random.randint(0, 100,size=(50,100), dtype= np.int64)

In [40]:
np.save('data3_in64', arr)

In [44]:
# 类型转换
arr1 = arr.astype(np.float32)
arr1

array([[95., 14., 90., ..., 45., 24., 84.],
       [89., 36., 82., ..., 33., 48., 60.],
       [49.,  8., 35., ..., 23., 93., 30.],
       ...,
       [82., 67.,  9., ..., 69., 96., 59.],
       [68.,  4., 50., ..., 49., 24., 14.],
       [30., 60., 17., ..., 63., 70., 72.]], dtype=float32)

# 7 数组运算

In [45]:
nd = np.random.randint(0,10,size=(3,5))

In [46]:
nd

array([[9, 5, 9, 3, 9],
       [2, 8, 2, 7, 1],
       [2, 9, 0, 9, 3]])

In [47]:
nd +2

array([[11,  7, 11,  5, 11],
       [ 4, 10,  4,  9,  3],
       [ 4, 11,  2, 11,  5]])

In [49]:
nd *2

array([[18, 10, 18,  6, 18],
       [ 4, 16,  4, 14,  2],
       [ 4, 18,  0, 18,  6]])

In [50]:
nd ** 2

array([[81, 25, 81,  9, 81],
       [ 4, 64,  4, 49,  1],
       [ 4, 81,  0, 81,  9]])

In [51]:
np.power(nd, 3)

array([[729, 125, 729,  27, 729],
       [  8, 512,   8, 343,   1],
       [  8, 729,   0, 729,  27]], dtype=int32)

In [52]:
nd /2

array([[4.5, 2.5, 4.5, 1.5, 4.5],
       [1. , 4. , 1. , 3.5, 0.5],
       [1. , 4.5, 0. , 4.5, 1.5]])

In [53]:
nd %2

array([[1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 1, 0, 1, 1]], dtype=int32)

In [54]:
nd // 2

array([[4, 2, 4, 1, 4],
       [1, 4, 1, 3, 0],
       [1, 4, 0, 4, 1]], dtype=int32)

In [55]:
nd > 5

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [False,  True, False,  True, False]])

In [58]:
nd == 2

array([[False, False, False, False, False],
       [ True, False,  True, False, False],
       [ True, False, False, False, False]])

In [59]:
nd += 100

In [60]:
nd

array([[109, 105, 109, 103, 109],
       [102, 108, 102, 107, 101],
       [102, 109, 100, 109, 103]])

In [61]:
nd -= 100

In [62]:
nd

array([[9, 5, 9, 3, 9],
       [2, 8, 2, 7, 1],
       [2, 9, 0, 9, 3]])

In [63]:
nd *= 100

In [64]:
nd

array([[900, 500, 900, 300, 900],
       [200, 800, 200, 700, 100],
       [200, 900,   0, 900, 300]])

In [66]:
nd //= 100

In [67]:
nd

array([[9, 5, 9, 3, 9],
       [2, 8, 2, 7, 1],
       [2, 9, 0, 9, 3]])

In [70]:
# nd /= 100 # 类型不同不支持

# 8 索引和切片

## 8.1一维数组

In [71]:
arr = np.random.randint(0, 100, size= 10)

In [72]:
arr

array([ 3,  5, 99,  4, 67, 29, 76, 74, 46, 61])

In [73]:
arr[[1,3,5]]

array([ 5,  4, 29])

In [74]:
arr[3:6]

array([ 4, 67, 29])

In [75]:
arr[3:6:2]

array([ 4, 29])

In [76]:
arr[::2]

array([ 3, 99, 67, 76, 46])

In [77]:
arr[::]

array([ 3,  5, 99,  4, 67, 29, 76, 74, 46, 61])

In [78]:
arr[:]

array([ 3,  5, 99,  4, 67, 29, 76, 74, 46, 61])

In [79]:
arr[::-2]

array([61, 74, 29,  4,  5])

In [80]:
arr[::-1]

array([61, 46, 74, 76, 29, 67,  4, 99,  5,  3])

## 二维

In [81]:
arr2 = np.random.randint(0,100,size=(3,5))

In [82]:
arr2

array([[99, 56, 61, 59, 61],
       [32, 63, 76, 31, 67],
       [56, 69,  4, 32, 55]])

In [83]:
arr2[0,2]

61

In [95]:
arr2[1,[1,2]] # 第二行的2、3元素

array([63, 76])

In [94]:
arr2[[1,2], ] # 取行

array([[32, 63, 76, 31, 67],
       [56, 69,  4, 32, 55]])

In [88]:
arr2[[1,2], [2,3]]

array([76, 32])

In [93]:
arr2[[1,2], 3:] # 连续的列

array([[31, 67],
       [32, 55]])

In [92]:
arr2[[1,2]][:,[2,4]] # 不连续的列


array([[76, 67],
       [ 4, 55]])

In [96]:
arr2[2,[2,3]] = 100 # 多重赋值

In [97]:
arr2

array([[ 99,  56,  61,  59,  61],
       [ 32,  63,  76,  31,  67],
       [ 56,  69, 100, 100,  55]])

## 花式索引

In [99]:
arr = np.random.randint(0, 100, size=20)
arr

array([25, 37,  0, 45, 94, 19, 61, 87, 49, 13, 43, 50, 64, 88, 23, 23, 53,
       52, 81, 93])

In [100]:
arr[arr > 60] # 过滤>60的数据

array([94, 61, 87, 64, 88, 81, 93])

In [108]:
arr[(arr > 60) | (arr < 30)] # 多个条件

array([25,  0, 94, 19, 61, 87, 13, 64, 88, 23, 23, 81, 93])

In [ ]:
arr = np.random.randint(0, 100, size=(5,5))
arr

In [112]:
arr[np.argsort(arr[:,2])]

array([[93,  3, 26,  7, 74],
       [89, 77, 32,  2, 23],
       [31, 45, 51,  3, 91],
       [16, 21, 52, 83,  6],
       [92, 52, 93, 27, 38]])

In [113]:
np.argsort(arr)

array([[3, 4, 2, 1, 0],
       [3, 0, 1, 2, 4],
       [4, 0, 1, 2, 3],
       [1, 3, 2, 4, 0],
       [3, 4, 1, 0, 2]], dtype=int64)

In [118]:
arr[:,2].argsort()

array([3, 0, 1, 2, 4], dtype=int64)

In [119]:
arr[arr[:,2].argsort()]

array([[93,  3, 26,  7, 74],
       [89, 77, 32,  2, 23],
       [31, 45, 51,  3, 91],
       [16, 21, 52, 83,  6],
       [92, 52, 93, 27, 38]])