# 改变数据形状

## 1 索引切片

In [2]:
import numpy as np
nd2 = np.random.randint(-5,15, size=(5,6))
nd2

array([[ 7, -3,  9, 11, 10,  9],
       [-3,  5, 10,  1, 13,  9],
       [-2,  6,  5, -3, 10, -5],
       [-3,  7, 13,  8, 13, 10],
       [ 3, 13, -2, 14,  1,  5]])

In [3]:
nd2[[1,3]]

array([[-3,  5, 10,  1, 13,  9],
       [-3,  7, 13,  8, 13, 10]])

In [4]:
nd2[:,[1,3,5]]

array([[-3, 11,  9],
       [ 5,  1,  9],
       [ 6, -3, -5],
       [ 7,  8, 10],
       [13, 14,  5]])

In [5]:
nd2[[1,3],][:,[1,3,5]] # 第2、4行，2，4，6列

array([[ 5,  1,  9],
       [ 7,  8, 10]])

In [11]:
nd2[np.ix_([1,3], [1,3,5])] # 跟上面等效

array([[ 5,  1,  9],
       [ 7,  8, 10]])

## 2 形状改变

In [13]:
nd2  = np.random.randint(0, 100 , size=(3,4)) # 三行四列的数据
display(nd2)

array([[58, 68, 91, 90],
       [67, 63,  6, 86],
       [93, 65, 63, 50]])

In [17]:
nd2.reshape(4,3) # 改为 4行3列

ValueError: cannot reshape array of size 12 into shape (1,)

In [19]:
nd2.reshape(2,6) # 改为 2行6列

array([[58, 68, 91, 90, 67, 63],
       [ 6, 86, 93, 65, 63, 50]])

In [24]:
nd2.reshape(-1,6) # -1表示占位符自动计算

array([[58, 68, 91, 90, 67, 63],
       [ 6, 86, 93, 65, 63, 50]])

In [26]:
nd2.reshape(-1) # 无参数的情况

array([58, 68, 91, 90, 67, 63,  6, 86, 93, 65, 63, 50])

## 2.2 数据叠加

In [34]:
arr1 = np.random.randint(0, 100, size=(2,4))
arr2 = np.random.randint(0, 100, size=(3,4))
display(arr1,arr2)

array([[47, 56, 64, 76],
       [ 9, 54, 13, 80]])

array([[58, 20, 34, 34],
       [46, 64, 83,  9],
       [53, 88, 34, 17]])

In [33]:
np.concatenate((arr1, arr2,arr2), ) # 默认行合并

array([[89, 72, 19,  7],
       [80, 11, 70, 14],
       [17, 81, 28,  8],
       [86, 70, 37, 13],
       [77,  7, 83, 37],
       [17, 81, 28,  8],
       [86, 70, 37, 13],
       [77,  7, 83, 37]])

In [35]:
arr1 = np.random.randint(0, 100, size=(3,4))
arr2 = np.random.randint(0, 100, size=(3,5))
display(arr1,arr2)

array([[20, 98, 43,  4],
       [56, 90, 22, 98],
       [26, 56, 30, 88]])

array([[60, 42, 69, 24, 81],
       [28, 82, 75,  6, 72],
       [56, 45, 24, 52, 66]])

In [39]:
np.concatenate((arr1, arr2),axis=-1 ) # axis=1  列合并 axis：维度

array([[20, 98, 43,  4, 60, 42, 69, 24, 81],
       [56, 90, 22, 98, 28, 82, 75,  6, 72],
       [26, 56, 30, 88, 56, 45, 24, 52, 66]])

In [40]:
np.concatenate((arr1, arr2),axis=1 ) # axis=-1  最后一个纬度 axis：维度

array([[20, 98, 43,  4, 60, 42, 69, 24, 81],
       [56, 90, 22, 98, 28, 82, 75,  6, 72],
       [26, 56, 30, 88, 56, 45, 24, 52, 66]])

## 2.3 数据拆分

In [43]:
nd = np.random.randint(0, 100, size=(6,9))
display(nd)
np.split(nd,2) # 平均拆分

array([[74, 63, 34, 63, 56, 16, 90, 88, 87],
       [57, 37, 15, 82,  2,  2, 51, 86, 53],
       [80, 27, 61,  5, 42, 97, 27, 84, 17],
       [11, 62, 41, 93, 12, 31, 96, 37,  0],
       [59, 65, 92, 33, 93, 96,  7, 98, 69],
       [18,  2, 87, 58, 83, 17, 13, 59, 92]])

[array([[74, 63, 34, 63, 56, 16, 90, 88, 87],
        [57, 37, 15, 82,  2,  2, 51, 86, 53],
        [80, 27, 61,  5, 42, 97, 27, 84, 17]]),
 array([[11, 62, 41, 93, 12, 31, 96, 37,  0],
        [59, 65, 92, 33, 93, 96,  7, 98, 69],
        [18,  2, 87, 58, 83, 17, 13, 59, 92]])]

In [55]:
display(nd)
np.split(nd,3,axis=-1) # 列拆分


array([[74, 63, 34, 63, 56, 16, 90, 88, 87],
       [57, 37, 15, 82,  2,  2, 51, 86, 53],
       [80, 27, 61,  5, 42, 97, 27, 84, 17],
       [11, 62, 41, 93, 12, 31, 96, 37,  0],
       [59, 65, 92, 33, 93, 96,  7, 98, 69],
       [18,  2, 87, 58, 83, 17, 13, 59, 92]])

[array([[74, 63, 34],
        [57, 37, 15],
        [80, 27, 61],
        [11, 62, 41],
        [59, 65, 92],
        [18,  2, 87]]),
 array([[63, 56, 16],
        [82,  2,  2],
        [ 5, 42, 97],
        [93, 12, 31],
        [33, 93, 96],
        [58, 83, 17]]),
 array([[90, 88, 87],
        [51, 86, 53],
        [27, 84, 17],
        [96, 37,  0],
        [ 7, 98, 69],
        [13, 59, 92]])]

In [56]:
np.split(nd,[1,4,5],axis=1) # 范围拆分

[array([[74],
        [57],
        [80],
        [11],
        [59],
        [18]]),
 array([[63, 34, 63],
        [37, 15, 82],
        [27, 61,  5],
        [62, 41, 93],
        [65, 92, 33],
        [ 2, 87, 58]]),
 array([[56],
        [ 2],
        [42],
        [12],
        [93],
        [83]]),
 array([[16, 90, 88, 87],
        [ 2, 51, 86, 53],
        [97, 27, 84, 17],
        [31, 96, 37,  0],
        [96,  7, 98, 69],
        [17, 13, 59, 92]])]

## 2.4数组转置

In [58]:
A  = np.random.randint(0, 100, size=(3,4))
display(A)

array([[30, 64, 86, 88],
       [44, 68, 26, 61],
       [63, 70, 88, 18]])

In [60]:
A.reshape(4,3)

array([[30, 64, 86],
       [88, 44, 68],
       [26, 61, 63],
       [70, 88, 18]])

In [61]:
A.T

array([[30, 44, 63],
       [64, 68, 70],
       [86, 26, 88],
       [88, 61, 18]])

In [63]:
np.transpose(A, axes=[1,0])

array([[30, 44, 63],
       [64, 68, 70],
       [86, 26, 88],
       [88, 61, 18]])

## 3.广播机制


In [67]:
arr1 = np.random.randint(0, 100, size=(5,3))
arr2 = np.arange(1,4)
display(arr1,arr2)

array([[33, 98, 37],
       [17, 63, 34],
       [54, 57, 64],
       [58, 88, 75],
       [30, 21, 45]])

array([1, 2, 3])

In [68]:
arr1+arr2

array([[ 34, 100,  40],
       [ 18,  65,  37],
       [ 55,  59,  67],
       [ 59,  90,  78],
       [ 31,  23,  48]])