# 改变数据形状

## 1 索引切片

In [69]:
import numpy as np
nd2 = np.random.randint(-5,15, size=(5,6))
nd2

array([[-4,  1,  4,  6,  1,  7],
       [-1, 14,  5, -5,  9, 14],
       [13,  9,  5, -2,  1, 10],
       [ 1, -2, -3, 10,  6, 14],
       [ 2,  7,  8,  1,  4,  9]])

In [70]:
nd2[[1,3]]

array([[-1, 14,  5, -5,  9, 14],
       [ 1, -2, -3, 10,  6, 14]])

In [71]:
nd2[:,[1,3,5]]

array([[ 1,  6,  7],
       [14, -5, 14],
       [ 9, -2, 10],
       [-2, 10, 14],
       [ 7,  1,  9]])

In [72]:
nd2[[1,3],][:,[1,3,5]] # 第2、4行，2，4，6列

array([[14, -5, 14],
       [-2, 10, 14]])

In [73]:
nd2[np.ix_([1,3], [1,3,5])] # 跟上面等效

array([[14, -5, 14],
       [-2, 10, 14]])

## 2 形状改变

In [74]:
nd2  = np.random.randint(0, 100 , size=(3,4)) # 三行四列的数据
display(nd2)

array([[11, 77, 38, 23],
       [27, 36, 75, 25],
       [ 1, 93, 42, 15]])

In [75]:
nd2.reshape(4,3) # 改为 4行3列

array([[11, 77, 38],
       [23, 27, 36],
       [75, 25,  1],
       [93, 42, 15]])

In [76]:
nd2.reshape(2,6) # 改为 2行6列

array([[11, 77, 38, 23, 27, 36],
       [75, 25,  1, 93, 42, 15]])

In [77]:
nd2.reshape(-1,6) # -1表示占位符自动计算

array([[11, 77, 38, 23, 27, 36],
       [75, 25,  1, 93, 42, 15]])

In [78]:
nd2.reshape(-1) # 无参数的情况

array([11, 77, 38, 23, 27, 36, 75, 25,  1, 93, 42, 15])

### 2.2 数据叠加

In [79]:
arr1 = np.random.randint(0, 100, size=(2,4))
arr2 = np.random.randint(0, 100, size=(3,4))
display(arr1,arr2)

array([[32,  2, 81, 76],
       [30, 37, 69, 56]])

array([[94,  3, 97, 60],
       [64,  0, 28, 91],
       [53, 60, 63, 31]])

In [80]:
np.concatenate((arr1, arr2,arr2), ) # 默认行合并

array([[32,  2, 81, 76],
       [30, 37, 69, 56],
       [94,  3, 97, 60],
       [64,  0, 28, 91],
       [53, 60, 63, 31],
       [94,  3, 97, 60],
       [64,  0, 28, 91],
       [53, 60, 63, 31]])

In [81]:
arr1 = np.random.randint(0, 100, size=(3,4))
arr2 = np.random.randint(0, 100, size=(3,5))
display(arr1,arr2)

array([[26, 26, 64, 52],
       [69,  6, 97, 24],
       [27, 20, 81, 53]])

array([[72,  7,  2, 89, 19],
       [19, 25,  5, 21, 75],
       [16, 18, 22, 94, 12]])

In [82]:
np.concatenate((arr1, arr2),axis=-1 ) # axis=1  列合并 axis：维度

array([[26, 26, 64, 52, 72,  7,  2, 89, 19],
       [69,  6, 97, 24, 19, 25,  5, 21, 75],
       [27, 20, 81, 53, 16, 18, 22, 94, 12]])

In [83]:
np.concatenate((arr1, arr2),axis=1 ) # axis=-1  最后一个纬度 axis：维度

array([[26, 26, 64, 52, 72,  7,  2, 89, 19],
       [69,  6, 97, 24, 19, 25,  5, 21, 75],
       [27, 20, 81, 53, 16, 18, 22, 94, 12]])

### 2.3 数据拆分

In [84]:
nd = np.random.randint(0, 100, size=(6,9))
display(nd)
np.split(nd,2) # 平均拆分

array([[27, 93, 42, 41,  8, 43, 27,  6, 13],
       [19, 13, 13, 57, 36, 25, 75, 18, 55],
       [40,  8, 19, 14, 19, 18, 66, 91, 71],
       [25, 66, 66, 72, 13, 11, 83, 68, 62],
       [23, 19, 84, 31, 17, 46, 83, 27, 71],
       [93, 57, 69, 83, 11, 50, 11, 77, 30]])

[array([[27, 93, 42, 41,  8, 43, 27,  6, 13],
        [19, 13, 13, 57, 36, 25, 75, 18, 55],
        [40,  8, 19, 14, 19, 18, 66, 91, 71]]),
 array([[25, 66, 66, 72, 13, 11, 83, 68, 62],
        [23, 19, 84, 31, 17, 46, 83, 27, 71],
        [93, 57, 69, 83, 11, 50, 11, 77, 30]])]

In [85]:
display(nd)
np.split(nd,3,axis=-1) # 列拆分


array([[27, 93, 42, 41,  8, 43, 27,  6, 13],
       [19, 13, 13, 57, 36, 25, 75, 18, 55],
       [40,  8, 19, 14, 19, 18, 66, 91, 71],
       [25, 66, 66, 72, 13, 11, 83, 68, 62],
       [23, 19, 84, 31, 17, 46, 83, 27, 71],
       [93, 57, 69, 83, 11, 50, 11, 77, 30]])

[array([[27, 93, 42],
        [19, 13, 13],
        [40,  8, 19],
        [25, 66, 66],
        [23, 19, 84],
        [93, 57, 69]]),
 array([[41,  8, 43],
        [57, 36, 25],
        [14, 19, 18],
        [72, 13, 11],
        [31, 17, 46],
        [83, 11, 50]]),
 array([[27,  6, 13],
        [75, 18, 55],
        [66, 91, 71],
        [83, 68, 62],
        [83, 27, 71],
        [11, 77, 30]])]

In [86]:
np.split(nd,[1,4,5],axis=1) # 范围拆分

[array([[27],
        [19],
        [40],
        [25],
        [23],
        [93]]),
 array([[93, 42, 41],
        [13, 13, 57],
        [ 8, 19, 14],
        [66, 66, 72],
        [19, 84, 31],
        [57, 69, 83]]),
 array([[ 8],
        [36],
        [19],
        [13],
        [17],
        [11]]),
 array([[43, 27,  6, 13],
        [25, 75, 18, 55],
        [18, 66, 91, 71],
        [11, 83, 68, 62],
        [46, 83, 27, 71],
        [50, 11, 77, 30]])]

### 2.4数组转置

In [87]:
A  = np.random.randint(0, 100, size=(3,4))
display(A)

array([[16, 73, 90, 11],
       [10, 95, 52,  1],
       [96, 50, 14, 78]])

In [88]:
A.reshape(4,3)

array([[16, 73, 90],
       [11, 10, 95],
       [52,  1, 96],
       [50, 14, 78]])

In [89]:
A.T

array([[16, 10, 96],
       [73, 95, 50],
       [90, 52, 14],
       [11,  1, 78]])

In [90]:
np.transpose(A, axes=[1,0])

array([[16, 10, 96],
       [73, 95, 50],
       [90, 52, 14],
       [11,  1, 78]])

## 3.广播机制


In [91]:
arr1 = np.random.randint(0, 100, size=(5,3))
arr2 = np.arange(1,4)
display(arr1,arr2)

array([[95, 33, 57],
       [ 0, 60, 32],
       [40, 99, 23],
       [66, 23, 67],
       [56, 41, 22]])

array([1, 2, 3])

In [92]:
arr1+arr2

array([[ 96,  35,  60],
       [  1,  62,  35],
       [ 41, 101,  26],
       [ 67,  25,  70],
       [ 57,  43,  25]])